---

- name: RKE2 agent and server tasks
  vars:
    rke2_common_caller_role_name: server
  ansible.builtin.include_role:
    name: rke2_common
    tasks_from: main

- name: Include task file add-pod-security-admission-config.yml
  ansible.builtin.include_tasks: add-pod-security-admission-config.yml

- name: Setup initial server
  ansible.builtin.include_tasks: first_server.yml
  when: inventory_hostname in groups['rke2_servers'][0]

- name: Setup other servers
  ansible.builtin.include_tasks: other_servers.yml
  when: inventory_hostname in groups['rke2_servers'][1:]

- name: Configure Utilities
  ansible.builtin.include_tasks: utilities.yml
