---
tarball_dir: "/usr/local"
rke2_tarball_url: ""
rke2_images_urls: []
rke2_channel: stable
audit_policy_config_file_path: ""
registry_config_file_path: ""
pod_security_admission_config_file_path: ""
add_iptables_rules: false
rke2_common_yum_repo:
  name: rancher-rke2-common
  description: "Rancher RKE2 Common Latest"
  baseurl: "https://rpm.rancher.io/rke2/stable/common/centos/$releasever/noarch"
  gpgcheck: true
  gpgkey: "https://rpm.rancher.io/public.key"
  enabled: yes

rke2_versioned_yum_repo:
  name: "rancher-rke2-v{{ rke2_version_majmin }}"  # noqa jinja[spacing]
  description: "Rancher RKE2 Version"
  baseurl: "https://rpm.rancher.io/rke2/stable/{{ rke2_version_majmin }}/centos/$releasever/$basearch"
  gpgcheck: true
  gpgkey: "https://rpm.rancher.io/public.key"
  enabled: yes

rke2_config:
  debug: true
  token: "K106ab408297e628770a18624ec042e3657993cf2847d15f2936a8d761b84a54216::server:e28a6613bed4b938372f56fa8dd3277a"
  tls-san:
    - "192.168.0.202"
    - "rke2vip.superasian.net"
  server: "https://rke2vip.superasian.net:9345"
