---
# Primary RKE2 server configuration parameters. Remove the curly braces ( {} ) and add your configuration.
# See https://docs.rke2.io/install/install_options/server_config/ for all configuration options.
#rke2_config: {}

# Example of possible rke2_config.
rke2_config:
 #  debug: true
 #  #selinux: true
 #  profile: cis-1.6
 #  kube-controller-manager-arg:
 #  - "tls-min-version=VersionTLS12"
 #  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
 #  kube-scheduler-arg:
 #  - "tls-min-version=VersionTLS12"
 #  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
 #  kube-apiserver-arg:
 #  - "tls-min-version=VersionTLS12"
 #  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
 #  - "enable-admission-plugins=ValidatingAdmissionWebhook,NodeRestriction,PodSecurityPolicy"
 #  - "request-timeout=300s"
 # # Enable only when auditing is enabled, blocks API when audit fails
 # #- "audit-log-mode=blocking-strict"

 #  kubelet-arg:
 #  - "feature-gates=DynamicKubeletConfig=false"
 #  - "protect-kernel-defaults=true"
 #  - "streaming-connection-idle-timeout=5m"

 # # Available in RKE2 1.21
 #  etcd-extra-env:
 #  - "ETCD_AUTO_TLS=true"
 #  - "ETCD_PEER_AUTO_TLS=true"

  # write-kubeconfig-mode: "0640"
  # token: "K1008e561729e450c076107549ab9ad8a63fa975ad73abc3de79145fa5e115d43b1::server:c493f1a06779ba746fadbadc76ea3045"
  # tls-san:
  # - "10.0.0.21"
  # - "infra01"
  # - "10.0.0.22"
  # - "infra02"
  # - "10.0.0.23"
  # - "infra03"
  # - "10.0.0.202"
  # - "rke2vip.superasian.net"
  # cni: calico
  # server: "https://10.0.0.202:9345"
  hosts:
    infra01:
    # node_labels:
    # - server1Label=true
      node_ip: "10.0.0.21"
      node_name: "infra01"
      bind_address: "10.0.0.21"
      advertise_address: "10.0.0.21"
    # node_external_ip: "52.52.52.52"
    node_taints:
    - CriticalAddonsOnly=true:NoSchedule
    # cloud_provider_name: "aws"
    infra02:
      # node_labels:
      #   - server2Label=true
      node_ip: "10.0.0.22"
      node_name: "infra02"
      bind_address: "10.0.0.22"
      advertise_address: "10.0.0.22"
      # node_external_ip: "52.52.52.52"
      node_taints:
      - CriticalAddonsOnly=true:NoSchedule
      # cloud_provider_name: "aws"
    infra03:
      # node_labels:
      #   - server3Label=true
      node_ip: "10.0.0.23"
      node_name: "infra03"
      bind_address: "10.0.0.23"
      advertise_address: "10.0.0.23"
      # node_external_ip: "52.52.52.52"
      node_taints:
      - CriticalAddonsOnly=true:NoSchedule
      # cloud_provider_name: "aws"

# See https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
# Add a policy configuration file by specifying the file path on the control host
# audit_policy_config_file_path: "{{ playbook_dir }}/sample_files/audit-policy.yaml"

# See https://docs.rke2.io/install/containerd_registry_configuration/
# Add a registry configuration file by specifying the file path on the control host
# registry_config_file_path: "{{ playbook_dir }}/sample_files/registries.yaml"

# See https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts
# Add manifest files by specifying the directory path on the control host
# manifest_config_file_path: "{{ playbook_dir }}/sample_files/manifest/"

# See https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates#exempting-required-rancher-namespaces
# Available in RKE2 1.25+
# Add a pod security admission config file by specifying the file path on the control host
# Requires config.yaml to include `- admission-control-config-file=/etc/rancher/rke2/pod-security-admission-config.yaml` in order for this to be honored
# pod_security_admission_config_file_path: "{{ playbook_dir }}/sample_files/pod-security-admission-config.yaml"
