---

# Primary RKE2 agent configuration parameters. Remove the curly braces ( {} ) and add your configuration.
# See https://docs.rke2.io/install/install_options/linux_agent_config/ for all configuration options.
#rke2_config: {}
  # debug: false

# See https://docs.rke2.io/install/containerd_registry_configuration/
# Add a registry configuration file by specifying the file path on the control host
# registry_config_file_path: "{{ playbook_dir }}/sample_files/registries.yaml"
rke2_config:
  debug: true
  cni: calico
  hosts:
    w0rk3r01:
      node_ip: "10.0.0.14"
      node_name: "w0rk3r01"
      bind_address: "10.0.0.14"
      advertise_address: "10.0.0.14"
    w0rk3r02:
      node_ip: "10.0.0.16"
      node_name: "w0rk3r02"
      bind_address: "10.0.0.16"
      advertise_address: "10.0.0.16"

