---
# Primary RKE2 server configuration parameters. Remove the curly braces ( {} ) and add your configuration.
# See https://docs.rke2.io/install/install_options/server_config/ for all configuration options.
#rke2_config: {}

# Example of possible rke2_config.
rke2_config:
  hosts:
    infra01:
      node_ip: "10.0.0.21"
      node_name: "infra01"
      bind_address: "10.0.0.21"
      advertise_address: "10.0.0.21"
    infra02:
      node_ip: "10.0.0.22"
      node_name: "infra02"
      bind_address: "10.0.0.22"
      advertise_address: "10.0.0.22"
    infra03:
      node_ip: "10.0.0.23"
      node_name: "infra03"
      bind_address: "10.0.0.23"
      advertise_address: "10.0.0.23"


# See https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
# Add a policy configuration file by specifying the file path on the control host
# audit_policy_config_file_path: "{{ playbook_dir }}/sample_files/audit-policy.yaml"

# See https://docs.rke2.io/install/containerd_registry_configuration/
# Add a registry configuration file by specifying the file path on the control host
# registry_config_file_path: "{{ playbook_dir }}/sample_files/registries.yaml"

# See https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts
# Add manifest files by specifying the directory path on the control host
# manifest_config_file_path: "{{ playbook_dir }}/sample_files/manifest/"

# See https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates#exempting-required-rancher-namespaces
# Available in RKE2 1.25+
# Add a pod security admission config file by specifying the file path on the control host
# Requires config.yaml to include `- admission-control-config-file=/etc/rancher/rke2/pod-security-admission-config.yaml` in order for this to be honored
# pod_security_admission_config_file_path: "{{ playbook_dir }}/sample_files/pod-security-admission-config.yaml"
